# Generated by Django 4.0 on 2022-01-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='ho',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='lo',
            new_name='login',
        ),
    ]
