# Generated by Django 4.0 on 2022-02-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_rename_ho_nurse_hospital_rename_lo_nurse_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='hospital',
            new_name='Hospital_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='log',
            new_name='login',
        ),
    ]
