# Generated by Django 4.0 on 2022-02-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_rename_hospital_nurse_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='approval_status',
        ),
    ]
