# Generated by Django 4.0 on 2022-02-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.login'),
        ),
    ]
