# Generated by Django 4.0 on 2022-02-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0005_alter_complaints_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.hospital'),
        ),
    ]
