# Generated by Django 4.0 on 2022-02-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_alter_schedule_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='hospital',
            new_name='Hospital',
        ),
    ]
