# Generated by Django 4.0 on 2022-02-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0007_alter_user_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customer',
        ),
    ]
