# Generated by Django 4.0 on 2022-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0008_rename_user_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='approvel_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proapp.vaccine'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recent_vaccinations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proapp.customer'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proapp.vaccine'),
        ),
    ]
