# Generated by Django 4.0 on 2022-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0009_rename_users_complaints_user_vaccine_approvel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_name',
            field=models.CharField(max_length=20),
        ),
    ]
