# Generated by Django 4.0 on 2022-02-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0010_alter_appointment_vaccine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proapp.vaccine'),
        ),
    ]
