# Generated by Django 4.0 on 2022-02-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0011_alter_reportcard_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proapp.customer'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proapp.vaccine'),
        ),
    ]
